insert into estados values ('AC','Acre','N');
insert into estados values ('AL','Alagoas','NE');
insert into estados values ('AP','Amapá','N');
insert into estados values ('AM','Amazonas','N');
insert into estados values ('BA','Bahia','NE');
insert into estados values ('CE','Ceará','NE');
insert into estados values ('DF','Distrito Federal','CO');
insert into estados values ('ES','Espírito Santo','SE');
insert into estados values ('GO','Goiás','CO');
insert into estados values ('MA','Maranhão','NE');
insert into estados values ('MT','Mato Grosso','CO');
insert into estados values ('MS','Mato Grosso do Sul','CO');
insert into estados values ('MG','Minas Gerais','SE');
insert into estados values ('PA','Pará','N');
insert into estados values ('PB','Paraíba','NE');
insert into estados values ('PR','Paraná','S');
insert into estados values ('PE','Pernambuco','NE');
insert into estados values ('PI','Piauí','NE');
insert into estados values ('RJ','Rio de Janeiro','SE');
insert into estados values ('RN','Rio Grande do Norte','NE');
insert into estados values ('RS','Rio Grande do Sul','S');
insert into estados values ('RO','Rondônia','N');
insert into estados values ('RR','Roraima','N');
insert into estados values ('SC','Santa Catarina','S');
insert into estados values ('SP','São Paulo','SE');
insert into estados values ('SE','Sergipe','NE');
insert into estados values ('TO','Tocantins','N');
