insert into autores values (1,'Sophia Angelides',null);
insert into autores values (2,'Mário Pedrosa',null);
insert into autores values (1002,'Otília Arantes',null);
insert into autores values (3,'Emílio F. Moran',null);
insert into autores values (4,'Jack R. Greene',null);
insert into autores values (5,'Antônio Chaves',null);
insert into autores values (6,'José Pedro de Oliveira Costa',null);
insert into autores values (7,'Ana Mae Barbosa',null);
insert into autores values (8,'Piero Comin-Chiaramonti',null);
insert into autores values (1008,'Celso Gomes',null);
insert into autores values (9,'Barão de Itararé',null);
insert into autores values (10,'Barão de Itararé',null);
insert into autores values (11,'Aziz Nacib AbSaber',null);
insert into autores values (12,'Maria L. Aragão',null);
insert into autores values (1012,'José Carlos S. Meihy ',null);
insert into autores values (13,'Eliane Garcindo Dayrell',null);
insert into autores values (1013,'Zilda Márcia Iokoi',null);
insert into autores values (14,'Maria Lígia Coelho Prado',null);
insert into autores values (15,'Tânia Maria Bessone',null);
insert into autores values (1015,'Tereza Aline Queiroz',null);
insert into autores values (16,'Dante Moreira Leite',null);
insert into autores values (17,'Nilza Nunes da Silva',null);
insert into autores values (18,'Ricardo Palma',null);
insert into autores values (19,'José Luiz Goldfarb',null);
insert into autores values (1019,'Márcia Ferraz',null);
insert into autores values (20,'Júlio César Rodrigues Pereira',null);
insert into autores values (21,'Flavio Aguiar',null);
insert into autores values (1021,'Sandra Guardini Vasconcelos',null);
insert into autores values (22,'Ângela Âncora da Luz',null);
insert into autores values (23,'Ulisses Capozoli',null);
insert into autores values (24,'Celia Pedrosa',null);
insert into autores values (25,'Annateresa Fabris',null);
insert into autores values (26,'Vagner Gonçalves da Silva',null);
insert into autores values (27,'Robert Foley',null);
insert into autores values (28,'William R. Torbert',null);
insert into autores values (29,'Jorge Antonio Ruedas de La Serna',null);
insert into autores values (30,'João Targino',null);
insert into autores values (31,'Antonio C Pacheco',null);
insert into autores values (1031,'Silva',null);
insert into autores values (32,'Hugo Segawa',null);
insert into autores values (33,'Jorge Wanderley',null);
insert into autores values (34,'Svetlana Alpers',null);
insert into autores values (35,'Elvira de Almeida',null);
insert into autores values (36,'Martin Warnke',null);
insert into autores values (37,'Francis Henrik Aubert',null);
insert into autores values (38,'Walter Junqueira Maciel',null);
insert into autores values (39,'Amâncio Friaça',null);
insert into autores values (1039,'Elisabete Dal Pino',null);
insert into autores values (2039,'Laerte Sodré Jr.',null);
insert into autores values (3039,'Vera Jatenco-Pereira',null);
insert into autores values (40,'José Luiz Signorini',null);
insert into autores values (1040,'Sérgio Luís Signorini',null);
insert into autores values (41,'Ana Maria Amaral',null);
insert into autores values (42,'Nina Ranieri',null);
insert into autores values (43,'Lisandro Nogueira',null);
insert into autores values (44,'Oswaldo Y. Tanaka',null);
insert into autores values (1044,'Cristina Melo',null);
insert into autores values (45,'Jorge Kazuo Yamamoto',null);
insert into autores values (46,'Alexandre Eulalio',null);
insert into autores values (1046,'Carlos Augusto Calil',null);
insert into autores values (47,'Elizabeth Höfling',null);
insert into autores values (1047,'Hélio Almeida Camargo',null);
insert into autores values (48,'Cilaine Alves',null);
insert into autores values (49,'Jeanne Marie M. de Freitas',null);
insert into autores values (50,'Maria Cecília França Lourenço',null);
insert into autores values (51,'Márcio Antonini Bernik',null);
insert into autores values (52,'Ana Maria Camargo',null);
insert into autores values (1052,'Rubens B. de Moraes',null);
insert into autores values (53,'Ruth Cardoso',null);
insert into autores values (1053,'Helena Sampaio',null);
insert into autores values (54,'Rosemarie E. Horch',null);
insert into autores values (1054,'Márcia Rosetto',null);
insert into autores values (55,'Marco Segre',null);
insert into autores values (1055,'Claudio Cohen ',null);
insert into autores values (56,'Isaias Raw',null);
insert into autores values (1056,'Leila Mannucci',null);
insert into autores values (2056,'Miriam Krasilchik',null);
insert into autores values (57,'Beaumarchais',null);
insert into autores values (58,'Barbara Weinstein',null);
insert into autores values (59,'Cecília Oliveira',null);
insert into autores values (1059,'Cláudia V. de Mattos',null);
insert into autores values (60,'Diana G. Vidal',null);
insert into autores values (1060,'Maria Lúcia S. Hilsdorf',null);
insert into autores values (61,'Christian Lohbauer',null);
insert into autores values (62,'Henrique Rattner',null);
insert into autores values (63,'Saúl Sosnowski',null);
insert into autores values (1063,'Jorge Schwartz',null);
insert into autores values (64,'Glauco Arbix',null);
insert into autores values (1064,'Álvaro Comin',null);
insert into autores values (2064,'Mauro Zilbovicius',null);
insert into autores values (3064,'Ricardo Abramovay',null);
insert into autores values (65,'Ligia Chiappini',null);
insert into autores values (1065,'Antonio Dimas',null);
insert into autores values (2065,'Berthold Zilly',null);
insert into autores values (66,'Cruz',null);
insert into autores values (1066,'Sousa',null);
insert into autores values (67,'José M. B. Carneiro',null);
insert into autores values (1067,'Ivette S. Ferreira',null);
insert into autores values (68,'Anna Catarina Hellmeister et alii',null);
insert into autores values (69,'Marion Verhaalen',null);
insert into autores values (70,'Edith Silveira Pompeu Piza',null);
insert into autores values (71,'Marlyse Meyer',null);
insert into autores values (72,'José Paulo Paes',null);
insert into autores values (73,'Luiz Tatit',null);
insert into autores values (74,'Annateresa Fabris',null);
insert into autores values (75,'Consuelo Novais Sampaio',null);
insert into autores values (76,'Sophia Angelides',null);
insert into autores values (77,'Anton P. Tchékhov',null);
insert into autores values (78,'Marcello Martinelli',null);
insert into autores values (79,'Comissão de Patrimônio Cultural da USP',null);
insert into autores values (80,'Carlos A. C. Lemos',null);
insert into autores values (81,'Yêdda Dias Lima',null);
insert into autores values (1081,'Zenir Campos Reis',null);
insert into autores values (82,'Heitor Frúgoli Jr.',null);
insert into autores values (83,'Denise Maria Cavalcante Gomes',null);
insert into autores values (84,'A. P. Tchékhov',null);
insert into autores values (85,'Elizabeth Höfling et alii',null);
insert into autores values (86,'Organização Mundial da Saúde',null);
insert into autores values (87,'Organização Mundial da Saúde',null);
insert into autores values (88,'Organização Mundial da Saúde',null);
insert into autores values (89,'Organização Mundial da Saúde',null);
insert into autores values (90,'Shozo Motoyama',null);
insert into autores values (91,'Heliana Angotti Salgueiro',null);
insert into autores values (92,'Maria José de A. Marcondes',null);
insert into autores values (93,'José Roberto do Amaral Lapa',null);
insert into autores values (94,'Amélia Império Hamburger et alii',null);
insert into autores values (95,'Alberto do Amaral Jr',null);
insert into autores values (1095,'Cláudia Moisés',null);
insert into autores values (96,'Cláudio Mubarac',null);
insert into autores values (97,'Charles Tilly',null);
insert into autores values (98,'Mary Douglas',null);
insert into autores values (99,'Marshall Sahlins',null);
insert into autores values (100,'Jean-Paul Brodeur',null);
insert into autores values (101,'Andre Nicolaï',null);
insert into autores values (102,'Tomás Antonio Gonzaga',null);
insert into autores values (103,'Michael Kunczik',null);
insert into autores values (104,'Francisco Maciel Silveira',null);
insert into autores values (105,'Miriam Moreira Leite',null);
insert into autores values (106,'Mirella Vieira Lima',null);
insert into autores values (107,'Luiz Renato Martins',null);
insert into autores values (108,'Ralf Dahrendorf',null);
insert into autores values (109,'Cleusa Rios P. Passos',null);
insert into autores values (110,'Francisca L. Azevedo',null);
insert into autores values (1110,'John Monteiro',null);
insert into autores values (111,'Danielle Forget',null);
insert into autores values (112,'Reinhard Bendix',null);
insert into autores values (113,'Tullo Vigevani',null);
insert into autores values (114,'Paulo Rónai',null);
insert into autores values (115,'Livio Tragtenberg',null);
insert into autores values (116,'Seiti Kaneko Endo',null);
insert into autores values (117,'Antonio Carlos Robert Moraes',null);
insert into autores values (118,'José Jaime da Cruz',null);
insert into autores values (119,'Maurício Segall',null);
insert into autores values (120,'Jacques Marcovitch',null);
insert into autores values (121,'João Baptista Borges Pereira',null);
insert into autores values (122,'Wander Melo Miranda',null);
insert into autores values (123,'Pascal Fouche',null);
insert into autores values (124,'Walnice N. Galvão',null);
insert into autores values (1124,'Oswaldo Galotti',null);
insert into autores values (125,'Marcos Antonio de Moraes',null);
insert into autores values (126,'Aracy Amaral',null);
insert into autores values (127,'Pascal Fouché',null);
insert into autores values (128,'Maria Inêz M.B. Pinto',null);
insert into autores values (129,'Maria Luiza Marcílio',null);
insert into autores values (130,'Zélia Maria Biasoli-Alves',null);
insert into autores values (1130,'Roseli Fischmann',null);
insert into autores values (131,'Boris Fausto',null);
insert into autores values (132,'August Strindberg',null);
insert into autores values (133,'Franco Lombardi',null);
insert into autores values (134,'Maria Hermínia T. de Almeida',null);
insert into autores values (135,'John Schulz',null);
insert into autores values (136,'Stendhal',null);
insert into autores values (137,'Nelson Marques',null);
insert into autores values (1137,'Luiz Menna-Barreto',null);
insert into autores values (138,'Jutta Gutberlet',null);
insert into autores values (139,'Oswaldo Paulo Forattini',null);
insert into autores values (140,'Oswaldo Paulo Forattini',null);
insert into autores values (141,'Nobue Myazaki',null);
insert into autores values (142,'Adolf Blumcke et alii',null);
insert into autores values (143,'Theodor Erhardt et alii',null);
insert into autores values (144,'G. W. F. Hegel',null);
insert into autores values (145,'G. W. F. Hegel',null);
insert into autores values (146,'G. W. F. Hegel',null);
insert into autores values (147,'Daniel Albernaz Acosta',null);
insert into autores values (148,'Marcel Raymond ',null);
insert into autores values (149,'João Faria',null);
insert into autores values (1149,'Vilma Arêas',null);
insert into autores values (2149,'Flávio Aguiar',null);
insert into autores values (150,'Fritz K. Ringer',null);
insert into autores values (151,'Ernst W. Hamburger',null);
insert into autores values (1151,'Cauê Matos',null);
insert into autores values (152,'Luis Henrique Sánchez',null);
insert into autores values (153,'Martin Dehmlow et alii',null);
insert into autores values (154,'Wilheim Heidkamp et alii',null);
insert into autores values (155,'Ezio Manzini',null);
insert into autores values (1155,'Carlo Vezzoli',null);
insert into autores values (156,'Leôncio Martins Rodrigues',null);
insert into autores values (157,'Nathan Wachtel',null);
insert into autores values (158,'Mikhail Bulgákov/Homero Freitas de Andrade',null);
insert into autores values (159,'Diana L. P. de Barros',null);
insert into autores values (1159,'José Luiz Fiorin',null);
insert into autores values (160,'Fernanda Arêas Peixoto',null);
insert into autores values (161,'Sérgio Milliet',null);
insert into autores values (162,'Sérgio Milliet',null);
insert into autores values (163,'Sérgio Milliet',null);
insert into autores values (164,'Sérgio Milliet',null);
insert into autores values (165,'Teotônio José Juzarte',null);
insert into autores values (166,'Nelly Novaes Coelho',null);
insert into autores values (167,'Fernando Capovilla',null);
insert into autores values (1167,'Walkiria D. Raphael',null);
insert into autores values (168,'Rifka Berezin',null);
insert into autores values (169,'Lenina Pomeranz',null);
insert into autores values (1169,'Jorge Miglioli',null);
insert into autores values (2169,'Gilberto Tadeu Lima',null);
insert into autores values (170,'Tânia Tomé',null);
insert into autores values (1170,'Mário J.de Oliveira',null);
insert into autores values (171,'Maria Cecília F. Lourenço',null);
insert into autores values (172,'Anna Maria Balogh',null);
insert into autores values (173,'Diana Luz Pessoa de Barros',null);
insert into autores values (174,'Rodolfo Hoffmann',null);
insert into autores values (175,'Maria Augusta da Costa Vieira',null);
insert into autores values (176,'Manoel de Souza',null);
insert into autores values (1176,'Silva',null);
insert into autores values (177,'Zilda Maria Zapparoli',null);
insert into autores values (1177,'André Camlong',null);
insert into autores values (178,'Emile Zola',null);
insert into autores values (179,'Manoel de Figueiredo Ferraz',null);
insert into autores values (180,'Beatriz Góis Dantas et alii',null);
insert into autores values (181,'Gilson L. Delgado',null);
insert into autores values (182,'Leon Glass',null);
insert into autores values (1182,'Michael Mackey',null);
insert into autores values (183,'Leopoldo Waizbort',null);
insert into autores values (184,'Joseph Frank',null);
insert into autores values (185,'Joseph Frank',null);
insert into autores values (186,'Joseph Frank',null);
insert into autores values (187,'C.P. Snow',null);
insert into autores values (188,'Laura Valladão de Mattos',null);
insert into autores values (189,'Jerusa Pires Ferreira',null);
insert into autores values (190,'Jerusa Pires Ferreira',null);
insert into autores values (191,'Magali Oliveira Fernandes',null);
insert into autores values (1191,'Sonia Montone',null);
insert into autores values (2191,'Carla Fernanda Fontana',null);
insert into autores values (3191,'Fábio Larsson',null);
insert into autores values (192,'Elisabeth Rochadel Torresini',null);
insert into autores values (193,'Leilah Santiago Bufrem',null);
insert into autores values (194,'Zilda M. Iokoi',null);
insert into autores values (1194,'Circe Maria Bittencourt ',null);
insert into autores values (195,'João Batista Gomes Neto et alii',null);
insert into autores values (196,'Nina Beatriz Stocco Ranieri',null);
insert into autores values (197,'Bruno Fregni Bassetto',null);
insert into autores values (198,'Edson A. Ticianelli',null);
insert into autores values (1198,'Ernesto R. Gonzalez',null);
insert into autores values (199,'Edgar Wind',null);
insert into autores values (200,'Sônia Maria de Amorim',null);
insert into autores values (201,'Silvio Dworecki',null);
insert into autores values (202,'ESALQ',null);
insert into autores values (1202,'Júlio S. Inglez de Souza',null);
insert into autores values (203,'ESALQ',null);
insert into autores values (1203,'Júlio S. Inglez de Souza',null);
insert into autores values (204,'ESALQ',null);
insert into autores values (1204,'Júlio S. Inglez de Souza',null);
insert into autores values (205,'Lineu Belico dos Reis',null);
insert into autores values (1205,'Semida Silveira',null);
insert into autores values (206,'José Goldemberg',null);
insert into autores values (207,'Fábio de Souza Andrade',null);
insert into autores values (208,'E.M. de Melo',null);
insert into autores values (1208,'Castro',null);
insert into autores values (209,'Artur Orlando',null);
insert into autores values (210,'Harold D.P. Graser et alii',null);
insert into autores values (211,'Lísias Nogueira Negrão',null);
insert into autores values (212,'Jean-Pierre Vernant',null);
insert into autores values (213,'Gordon R. Slemon',null);
insert into autores values (214,'Carlos Alberto Zeron',null);
insert into autores values (215,'José Wilton Guerra',null);
insert into autores values (216,'Renata da Silva Simões',null);
insert into autores values (217,'José Wilton N. Guerra',null);
insert into autores values (1217,'Renata da Silva Simões',null);
insert into autores values (218,'José Wilton N. Guerra',null);
insert into autores values (1218,'Renata da Silva Simões ',null);
insert into autores values (219,'Donaldo Schüler',null);
insert into autores values (220,'Joaquim Alves de Aguiar',null);
insert into autores values (221,'Anselm Strauss',null);
insert into autores values (222,'Nachman Falbel',null);
insert into autores values (223,'Danton Jobim',null);
insert into autores values (224,'André Singer',null);
insert into autores values (225,'Anthony Giddens',null);
insert into autores values (226,'André Guinier',null);
insert into autores values (227,'Maria Lúcia Lebrão',null);
insert into autores values (228,'Francis L.K. Hsu',null);
insert into autores values (229,'R. H. Lowe-McConnell',null);
insert into autores values (230,'Paulo César Masiero',null);
insert into autores values (231,'Mauro Leonel',null);
insert into autores values (232,'Hilário Franco Júnior',null);
insert into autores values (233,'Villiers de lIsle-Adam',null);
insert into autores values (234,'John Schulz',null);
insert into autores values (235,'Tae Suzuki',null);
insert into autores values (236,'Carlos da Silva Lacaz',null);
insert into autores values (1236,'Berta R. de Mazzieri',null);
insert into autores values (237,'Szulim Ber Zyngier et alii',null);
insert into autores values (238,'Boris Fausto',null);
insert into autores values (239,'Feres Lourenço Khoury',null);
insert into autores values (240,'István Jancsó',null);
insert into autores values (1240,'Iris Kantor',null);
insert into autores values (241,'Vilém Flusser',null);
insert into autores values (242,'Daisy Peccinini',null);
insert into autores values (243,'Renato Mezan',null);
insert into autores values (244,'F. W. J. Schelling',null);
insert into autores values (245,'E. M. de Melo',null);
insert into autores values (1245,'Castro',null);
insert into autores values (246,'Grupo de Reelaboração do Ensino de Física',null);
insert into autores values (247,'Grupo de Reelaboração do Ensino de Física',null);
insert into autores values (248,'Grupo de Reelaboração do Ensino de Física',null);
insert into autores values (249,'Willi Bolle',null);
insert into autores values (250,'Renina Katz',null);
insert into autores values (1250,'Amélia Hamburger',null);
insert into autores values (251,'Maria Nazaré de Camargo Pacheco Amaral',null);
insert into autores values (252,'José R. Pirani',null);
insert into autores values (1252,'Marilda C. Laurino',null);
insert into autores values (253,'Regina Machado Leão',null);
insert into autores values (254,'José de Souza Martins',null);
insert into autores values (255,'Robert Klein',null);
insert into autores values (256,'Mário Pedrosa',null);
insert into autores values (1256,'Otília Arantes',null);
insert into autores values (257,'Annateresa Fabris',null);
insert into autores values (258,'Norberto de Abreu',null);
insert into autores values (1258,'Silva Neto',null);
insert into autores values (259,'Noemi Moritz Kon',null);
insert into autores values (260,'Paulo Santilli',null);
insert into autores values (261,'Max Weber',null);
insert into autores values (262,'Héctor Olea',null);
insert into autores values (263,'A. P. Tchékhov',null);
insert into autores values (264,'Iberê Camargo',null);
insert into autores values (1264,'Augusto Massi',null);
insert into autores values (265,'Jurandir L. Sanches Ross',null);
insert into autores values (266,'Cees Passchier',null);
insert into autores values (1266,'John Myers',null);
insert into autores values (2266,'Alfred Kröner',null);
insert into autores values (267,'Charles Rosen',null);
insert into autores values (268,'Márcia Westphal',null);
insert into autores values (1268,'Eurivaldo S. Almeida',null);
insert into autores values (269,'Osvando J. de Morais',null);
insert into autores values (270,'Maria Delizete B. Spallicci',null);
insert into autores values (1270,'Maria Tereza Zulini da Costa',null);
insert into autores values (2270,'Marta Maria Melleiro',null);
insert into autores values (271,'Marco Buti',null);
insert into autores values (1271,'Anna Letycia',null);
insert into autores values (272,'Pedro Luis Puntoni',null);
insert into autores values (273,'Roney Cytrynowicz',null);
insert into autores values (274,'John Manuel Monteiro',null);
insert into autores values (275,'Comissão de Patrimônio Cultural',null);
insert into autores values (276,'Leon Kossovitch',null);
insert into autores values (277,'Hélio Vinci',null);
insert into autores values (278,'Aurora Fornoni Bernardini',null);
insert into autores values (279,'José Eduardo Martins',null);
insert into autores values (280,'Isabella Cabral',null);
insert into autores values (1280,'M. A. Amaral Rezende',null);
insert into autores values (281,'Fernando Olavo Franciss',null);
insert into autores values (282,'Boris Fausto',null);
insert into autores values (283,'Décio de Almeida Prado',null);
insert into autores values (284,'Leslie Bethell',null);
insert into autores values (285,'Leslie Bethell',null);
insert into autores values (286,'Leslie Bethell',null);
insert into autores values (287,'Leslie Bethell',null);
insert into autores values (288,'Leslie Bethell',null);
insert into autores values (289,'Ana Maria Goldfarb',null);
insert into autores values (1289,'Carlos Maia ',null);
insert into autores values (290,'Anatol Rosenfeld',null);
insert into autores values (291,'Gerson Moura',null);
insert into autores values (292,'Boris Fausto',null);
insert into autores values (293,'Mark J. Curran',null);
insert into autores values (294,'Carmen Bernand',null);
insert into autores values (1294,'Serge Gruzinski',null);
insert into autores values (295,'Tamás Szmrecsányi',null);
insert into autores values (1295,'José R. A. Lapa',null);
insert into autores values (296,'Sérgio S. Silva',null);
insert into autores values (1296,'Tamás Szmrecsányi',null);
insert into autores values (297,'Tamás Szmrecsányi',null);
insert into autores values (1297,'Ricardo Maranhão',null);
insert into autores values (298,'Tamás Szmrecsányi',null);
insert into autores values (1298,'Wilson Suzigan',null);
insert into autores values (299,'Tamás Szmrecsányi',null);
insert into autores values (300,'Mariana Kawall L. Ferreira',null);
insert into autores values (301,'Luiz Felipe Pondé',null);
insert into autores values (302,'Louis Dumont',null);
insert into autores values (303,'Renato Janine Ribeiro',null);
insert into autores values (304,'John Flourinoy Montgomery',null);
insert into autores values (305,'Anita Waingort Novinsky',null);
insert into autores values (1305,'Diane Kuperman',null);
insert into autores values (306,'Lourdes Sola',null);
insert into autores values (307,'Maria Adélia Aparecida de Souza',null);
insert into autores values (308,'Edward Lopes',null);
insert into autores values (309,'Haroldo de Campos',null);
insert into autores values (310,'Edgard Carone',null);
insert into autores values (311,'Orlando da Costa Ferreira',null);
insert into autores values (312,'Nestor Goulart Reis',null);
insert into autores values (313,'Vera Lúcia Felício',null);
insert into autores values (314,'Abdelmalek Sayad',null);
insert into autores values (315,'Leopoldo M. Bernucci',null);
insert into autores values (316,'Walter de Paula Lima',null);
insert into autores values (317,'Rui Barbosa',null);
insert into autores values (318,'Berta G. Ribeiro',null);
insert into autores values (319,'Peter Rivière',null);
insert into autores values (320,'Luiz Beltrão',null);
insert into autores values (321,'Carlos Fausto',null);
insert into autores values (322,'Maria das Graças Carvalho Ferriani',null);
insert into autores values (323,'Federico Neiburg',null);
insert into autores values (324,'GEPEQ-USP',null);
insert into autores values (325,'GEPEQ-USP',null);
insert into autores values (326,'GEPEQ-USP',null);
insert into autores values (327,'GEPEQ-USP',null);
insert into autores values (328,'GEPEQ-USP',null);
insert into autores values (329,'GEPEQ-USP',null);
insert into autores values (330,'GEPEQ-USP',null);
insert into autores values (331,'GEPEQ-USP',null);
insert into autores values (332,'GEPEQ-USP',null);
insert into autores values (333,'GEPEQ-USP',null);
insert into autores values (334,'GEPEQ-USP',null);
insert into autores values (335,'Tânia AielloTsu',null);
insert into autores values (336,'Luiz Costa Lima',null);
insert into autores values (337,'Eurico Cabral de Oliveira',null);
insert into autores values (338,'Walter J. Maciel',null);
insert into autores values (339,'Juan G. Roederer',null);
insert into autores values (340,'Sílvio Roberto de Azevedo Salinas',null);
insert into autores values (341,'Celso Favaretto',null);
insert into autores values (342,'M.A. Amaral Rezende',null);
insert into autores values (343,'Lazslo Antonio Ávila',null);
insert into autores values (344,'Franco Cenni',null);
insert into autores values (345,'João Baptista Borges Pereira',null);
insert into autores values (346,'A. P. Tchékhov',null);
insert into autores values (347,'Armando Sérgio da Silva',null);
insert into autores values (348,'Tadeusz Lewowicki',null);
insert into autores values (1348,'Helena Singer',null);
insert into autores values (2348,'Jayme Murahovschi',null);
insert into autores values (349,'Nelson Saldanha',null);
insert into autores values (350,'Denise Dias Barros',null);
insert into autores values (351,'Francis Utéza',null);
insert into autores values (352,'Almerinda da Silva Lopes',null);
insert into autores values (353,'Sylvia Caiuby Novaes',null);
insert into autores values (354,'George Tsebelis',null);
insert into autores values (355,'Viviana Bosi Concagh',null);
insert into autores values (356,'Ana Maria Paulino',null);
insert into autores values (357,'Alceu Amoroso Lima',null);
insert into autores values (358,'Bernardo Kucinski',null);
insert into autores values (359,'Cátia Aida Silva',null);
insert into autores values (360,'Vera Penteado Coelho',null);
insert into autores values (361,'Nachman Falbel',null);
insert into autores values (362,'José Alberto Neves Candeias',null);
insert into autores values (363,'Aguinaldo José Gonçalves',null);
insert into autores values (364,'Cláudia Valladão de Mattos',null);
insert into autores values (365,'João da Silva',null);
insert into autores values (366,'Laurita Salles',null);
insert into autores values (367,'Ricardo Iannace',null);
insert into autores values (368,'Hélio Lopes',null);
insert into autores values (369,'Anatol Rosenfeld',null);
insert into autores values (1369,'Nanci Fernandes',null);
insert into autores values (2369,'J. Guinsburg ',null);
insert into autores values (370,'Anatol Rosenfeld',null);
insert into autores values (371,'Nilce SantAnna Martins',null);
insert into autores values (372,'Pierre Bourdieu',null);
insert into autores values (1372,'Sergio Miceli',null);
insert into autores values (373,'Lourdes Sola',null);
insert into autores values (1373,'Leda M. Paulani',null);
insert into autores values (374,'João da Silva',null);
insert into autores values (375,'Vários Autores',null);
insert into autores values (376,'Vários Autores',null);
insert into autores values (377,'Michel Arrivé',null);
insert into autores values (378,'José Maria R. Ramos',null);
insert into autores values (379,'Francisco Achcar',null);
insert into autores values (380,'Segismundo Spina',null);
insert into autores values (381,'Luiz Roncari',null);
insert into autores values (382,'José Aderaldo Castello',null);
insert into autores values (383,'José Aderaldo Castello',null);
insert into autores values (384,'Sandra Nitrini',null);
insert into autores values (385,'Ligia Chiappini',null);
insert into autores values (1385,'Flávio Wolf de Aguiar',null);
insert into autores values (386,'Ernst Robert Curtius',null);
insert into autores values (387,'Marcio Meira',null);
insert into autores values (388,'Catulo',null);
insert into autores values (389,'Mancur Olson',null);
insert into autores values (390,'Otília Arantes',null);
insert into autores values (391,'Dominique Tilkin Gallois',null);
insert into autores values (392,'Solival Menezes',null);
insert into autores values (393,'Harold Bright Maynard',null);
insert into autores values (394,'Harold Bright Maynard',null);
insert into autores values (395,'Harold Bright Maynard',null);
insert into autores values (396,'Harold Bright Maynard',null);
insert into autores values (397,'Harold Bright Maynard',null);
insert into autores values (398,'Harold Bright Maynard',null);
insert into autores values (399,'Harold Bright Maynard',null);
insert into autores values (400,'Harold Bright Maynard',null);
insert into autores values (401,'Harold Bright Maynard',null);
insert into autores values (402,'Rogério Lacaz-Ruiz',null);
insert into autores values (403,'Yudith Rosenbaum',null);
insert into autores values (404,'Alcir Pécora',null);
insert into autores values (405,'Arlindo Machado',null);
insert into autores values (406,'Marco Buti',null);
insert into autores values (407,'Cláudia de Arruda Campos',null);
insert into autores values (408,'Tomás Antonio Gonzaga',null);
insert into autores values (409,'Maria Ligia C. Prado',null);
insert into autores values (1409,'Diana G. Vidal',null);
insert into autores values (410,'Ricardo Ribeiro Rodrigues',null);
insert into autores values (1410,'Hermógenes F. Leitão Filho',null);
insert into autores values (411,'Maria do Carmo Campos',null);
insert into autores values (412,'Michel Paty',null);
insert into autores values (413,'Manuel Dias de Oliveira',null);
insert into autores values (414,'Maurício Nogueira Lima',null);
insert into autores values (415,'Walter F. Wreszinski',null);
insert into autores values (416,'Francis Haskell',null);
insert into autores values (417,'Ivan Teixeira',null);
insert into autores values (418,'Ernesto Lima-Gonçalves',null);
insert into autores values (419,'E. H. Gombrich',null);
insert into autores values (420,'Vavy Pacheco Borges',null);
insert into autores values (421,'Luiza Franco Moreira',null);
insert into autores values (422,'Sandra Reimão',null);
insert into autores values (423,'Fábio Wanderley Reis',null);
insert into autores values (424,'Henrique Rattner',null);
insert into autores values (425,'Hayden White',null);
insert into autores values (426,'Yudith Rosenbaum',null);
insert into autores values (427,'Antonio Candido',null);
insert into autores values (428,'Mark Blaug',null);
insert into autores values (429,'Rolf Enderlein',null);
insert into autores values (430,'Margarida Maria K. Kunsch',null);
insert into autores values (1430,'Roseli Fischann',null);
insert into autores values (431,'Maria Luiza Tucci Carneiro',null);
insert into autores values (432,'André da Silva Gomes',null);
insert into autores values (433,'Carlos Lacerda',null);
insert into autores values (434,'Egon Schaden',null);
insert into autores values (435,'Fernando Lefévre',null);
insert into autores values (436,'Claudio Garcia',null);
insert into autores values (437,'Mário Pedrosa',null);
insert into autores values (1437,'Otília Arantes',null);
insert into autores values (438,'Susan K. Besse',null);
insert into autores values (439,'Edilson de Lima',null);
insert into autores values (440,'Peter William Atkins',null);
insert into autores values (441,'Marjorie Perloff',null);
insert into autores values (442,'João Teodoro D Olim Marote',null);
insert into autores values (443,'Edna Tarabori Calobrezi',null);
insert into autores values (444,'Herman Braet',null);
insert into autores values (1444,'Werner Verbeke',null);
insert into autores values (445,'Luiza Franco Moreira',null);
insert into autores values (446,'Liliana Rolfsen Petrilli Segnini',null);
insert into autores values (447,'Murilo Marcondes de Moura',null);
insert into autores values (448,'Stuart Davies',null);
insert into autores values (449,'Stuart Davies',null);
insert into autores values (450,'Stuart Davies',null);
insert into autores values (451,'Maria Lucia Alexandrino Segall',null);
insert into autores values (452,'Maria Cecília França Lourenço',null);
insert into autores values (453,'Régis Duprat',null);
insert into autores values (454,'Régis Duprat',null);
insert into autores values (455,'Mário de Andrade',null);
insert into autores values (456,'Maria Helena Souza Patto',null);
insert into autores values (457,'José G. Magnani',null);
insert into autores values (1457,'Lilian Lucca Torres',null);
insert into autores values (458,'Nicolai Vassilievitch Gogol',null);
insert into autores values (1458,'Arlet Cavaliere',null);
insert into autores values (459,'Lúcia Nagib',null);
insert into autores values (460,'Marcel Proust',null);
insert into autores values (461,'Milton Santos',null);
insert into autores values (462,'Oracy Nogueira',null);
insert into autores values (463,'Mariarosaria Fabris',null);
insert into autores values (464,'Mariarosaria Fabris',null);
insert into autores values (465,'Mario Vieira de Mello',null);
insert into autores values (466,'Marcos Magalhães',null);
insert into autores values (1466,'Antonio Carlos Lima',null);
insert into autores values (467,'Raymond Firth',null);
insert into autores values (468,'Mário Fannucchi',null);
insert into autores values (469,'Paulo Franchetti',null);
insert into autores values (470,'Pierre Verger',null);
insert into autores values (471,'David H. Bayley',null);
insert into autores values (1471,'Jerome H. Skolnick',null);
insert into autores values (472,'Francis Henrik Aubert',null);
insert into autores values (473,'Marianna Monteiro',null);
insert into autores values (474,'Heliana Comin Vargas',null);
insert into autores values (1474,'Helena Ribeiro',null);
insert into autores values (475,'César Polcino Milies',null);
insert into autores values (1475,'Sônia Pitta Coelho',null);
insert into autores values (476,'Comissão de Patrimônio Cultural',null);
insert into autores values (477,'Ivan Teixeira',null);
insert into autores values (478,'Homero',null);
insert into autores values (479,'Maria Silva Betti',null);
insert into autores values (480,'Boris Kossoy',null);
insert into autores values (1480,'Maria Luiza T. Carneira',null);
insert into autores values (481,'Lucrécia D`Aléssio Ferrara',null);
insert into autores values (482,'Arnaldo Pedroso dHorta',null);
insert into autores values (483,'Pedro Alberto Morettin',null);
insert into autores values (484,'Isaac Newton',null);
insert into autores values (485,'Matt Young',null);
insert into autores values (486,'Peter A. Pyhrr',null);
insert into autores values (487,'Jacques Testart',null);
insert into autores values (488,'David H. Bayley',null);
insert into autores values (489,'Beatriz Sarlo',null);
insert into autores values (490,'Maria Betânia Amoroso',null);
insert into autores values (491,'Guilherme Simões Gomes Jr.',null);
insert into autores values (492,'Orlando de Miranda',null);
insert into autores values (493,'Heitor Megale et alli',null);
insert into autores values (494,'Silvio Soares Macedo',null);
insert into autores values (1494,'Adauto Pereira',null);
insert into autores values (495,'Leôncio Martins Rodrigues',null);
insert into autores values (496,'Januário de Andrade',null);
insert into autores values (497,'Ruth Sprung Tarasantchi',null);
insert into autores values (498,'Jose Lima de Fiqueiredo',null);
insert into autores values (1498,'Andressa Pinter dos Santos',null);
insert into autores values (2498,'Noriyoshi Yamaguti',null);
insert into autores values (3498,'Roberto Ávila Bernardes',null);
insert into autores values (4498,'Carmen Lúcia Del Bianco Rossi-Wongtschowski',null);
insert into autores values (499,'Alfred Russel Wallace',null);
insert into autores values (500,'Joseph Frank',null);
insert into autores values (501,'Lenina Pomeranz',null);
insert into autores values (502,'Maria N. de Camargo Pacheco Amaral et alii',null);
insert into autores values (503,'Maria Angela Fornoni',null);
insert into autores values (1503,'Gergley Andres Julio Szabó',null);
insert into autores values (2503,'Elaine Aparecida Del Lama ',null);
insert into autores values (504,'Ruth Sprung Tarasantchi',null);
insert into autores values (505,'Gilberto Mazzoleni',null);
insert into autores values (506,'Sonia F. Dorta',null);
insert into autores values (1506,'Marília Xavier Cury',null);
insert into autores values (507,'François Villon',null);
insert into autores values (508,'Augusto Massi',null);
insert into autores values (509,'Segismundo Spina',null);
insert into autores values (510,'Adma Muhana',null);
insert into autores values (511,'trad. Mário Laranjeira',null);
insert into autores values (512,'Roger Bastide',null);
insert into autores values (513,'Mário Laranjeira',null);
insert into autores values (514,'Robert A. Dahl',null);
insert into autores values (515,'Jerome H. Skolnick',null);
insert into autores values (1515,'David H. Bailey',null);
insert into autores values (516,'Michel Tory',null);
insert into autores values (1516,'Norval Morris',null);
insert into autores values (517,'Jean-Claude Monet',null);
insert into autores values (518,'Mário Pedrosa',null);
insert into autores values (1518,'Otília Arantes',null);
insert into autores values (519,'John B. Miner',null);
insert into autores values (1519,'George A. Steiner',null);
insert into autores values (520,'José Carlos Avellar',null);
insert into autores values (521,'Milton Santos',null);
insert into autores values (522,'Bernard Lepetit',null);
insert into autores values (523,'Stephen Greenblatt',null);
insert into autores values (524,'Antonio Porro',null);
insert into autores values (525,'Luís Donisete Grupioni',null);
insert into autores values (1525,'Lux Vidal',null);
insert into autores values (2525,'Roseli Fischmann',null);
insert into autores values (526,'Silvio Soares Macedo',null);
insert into autores values (1526,'Fábio Robba',null);
insert into autores values (527,'Oracy Nogueira',null);
insert into autores values (528,'Isaias Pessotti',null);
insert into autores values (529,'André Luiz Baracchini Centola et alii',null);
insert into autores values (530,'Bento Prado Júnior',null);
insert into autores values (531,'Tobias Monteiro',null);
insert into autores values (532,'Aziz AbSaber',null);
insert into autores values (1532,'Clarita Müller-Plantenberg',null);
insert into autores values (533,'Isaac Newton',null);
insert into autores values (534,'Josif Frenkel',null);
insert into autores values (535,'Luiz Miranda',null);
insert into autores values (1535,'Belmiro Castro',null);
insert into autores values (2535,'Björn Kjerfve',null);
insert into autores values (536,'Anatol Rosenfeld',null);
insert into autores values (537,'Carlos Alberto Barbosa Dantas',null);
insert into autores values (538,'Barbosa Lima Sobrinho',null);
insert into autores values (539,'Marcia L. Stigum',null);
insert into autores values (540,'Regis de Castro Andrade',null);
insert into autores values (541,'Soraia Maria Silva',null);
insert into autores values (542,'Robert M. Sherwood',null);
insert into autores values (543,'Eleonora H. Antunes',null);
insert into autores values (1543,'Lúcia S. Barbosa',null);
insert into autores values (2543,'Lygia de França Pereira',null);
insert into autores values (544,'Adilson Avansi de Abreu',null);
insert into autores values (545,'Henrique Oswald',null);
insert into autores values (546,'Leonel Itaussu Almeida Mello',null);
insert into autores values (547,'Heloisa Vilhena de Araújo',null);
insert into autores values (548,'Francisca Azevedo',null);
insert into autores values (1548,'John Monteiro',null);
insert into autores values (549,'Maria Cristina Wolff de Carvalho',null);
insert into autores values (550,'Giuseppe Ungaretti',null);
insert into autores values (551,'Glauco Arbix',null);
insert into autores values (1551,'Mauro Zilbovicius',null);
insert into autores values (2551,'Ricardo Abramovay',null);
insert into autores values (552,'João da Silva',null);
insert into autores values (553,'Flávia Camargo Toni',null);
insert into autores values (554,'Murilo Mendes',null);
insert into autores values (555,'Simon Schwartzman',null);
insert into autores values (556,'Regina M. Almeida',null);
insert into autores values (1556,'Vera Lúcia C. G. Santos',null);
insert into autores values (557,'José de Souza Martins',null);
insert into autores values (558,'Sandra Lencioni',null);
insert into autores values (559,'Angelica de Moraes',null);
insert into autores values (560,'Vera Martins da Silva',null);
insert into autores values (561,'Heloísa B. Holanda',null);
insert into autores values (1561,'Maria H. Capelato',null);
insert into autores values (562,'Teresa Aline Pereira de Queiroz',null);
insert into autores values (563,'Eliot Freidson',null);
insert into autores values (564,'Renina Katz',null);
insert into autores values (565,'Sérgio Figueiredo Ferretti',null);
insert into autores values (566,'Beatriz Góis Dantas',null);
insert into autores values (567,'Giselle Beiguelman-Messina',null);
insert into autores values (568,'Eugênio Fernandes',null);
insert into autores values (569,'Moacyr Lobo da Costa',null);
insert into autores values (570,'Robert Darnton',null);
insert into autores values (1570,'Daniel Roche',null);
insert into autores values (571,'Vagner Camilo',null);
insert into autores values (572,'Rosângela Rennó',null);
insert into autores values (573,'Céline Sachs',null);
insert into autores values (574,'Marcília Medrado Faria',null);
insert into autores values (1574,'Adib Jatene',null);
insert into autores values (575,'Maria Lúcia Cacciola',null);
insert into autores values (576,'Oswaldo Paulo Forattini',null);
insert into autores values (577,'Robert M. Levine',null);
insert into autores values (578,'Ernesto Lima-Gonçalves',null);
insert into autores values (579,'Zipora Rubinstein',null);
insert into autores values (580,'Siegbert Zanettini',null);
insert into autores values (581,'Lucrécia DAlessio Ferrara',null);
insert into autores values (582,'Heloísa Rodrigues Fernandes',null);
insert into autores values (583,'Olaya S. M. Portella Hanashiro',null);
insert into autores values (584,'Edmund Ronald Leach',null);
insert into autores values (585,'Lourival Holanda',null);
insert into autores values (586,'J. Guinsburg',null);
insert into autores values (1586,'Plinio Martins Filho',null);
insert into autores values (587,'Northrop Frye',null);
insert into autores values (588,'Dino Preti',null);
insert into autores values (589,'Héctor Aguilar Camín',null);
insert into autores values (1589,'Lorenzo Meyer',null);
insert into autores values (590,'Michael Baxandall',null);
insert into autores values (591,'Cacilda Teixeira Costa',null);
insert into autores values (592,'Louis Marin',null);
insert into autores values (593,'Marlyse Meyer',null);
insert into autores values (594,'Maria Helena Nery Garcez',null);
insert into autores values (595,'Edvaldo P. Lima (org.)',null);
insert into autores values (596,'Aracy Amaral',null);
insert into autores values (597,'Aracy Amaral',null);
insert into autores values (598,'Alvaro Antonio Zini Jr.',null);
insert into autores values (599,'Ana Maria Amaral',null);
insert into autores values (600,'Alcir Pécora',null);
insert into autores values (601,'João Roberto Faria',null);
insert into autores values (602,'Armando de Oliveira Fortuna',null);
insert into autores values (603,'Annelise Strauss',null);
insert into autores values (604,'Aracy Lopes Silva',null);
insert into autores values (1604,'Luis D. B. Grupioni',null);
insert into autores values (605,'Marcelo Otávio C. Gomes',null);
insert into autores values (606,'Bernard Schmitt',null);
insert into autores values (607,'Walter F. Wreszinski',null);
insert into autores values (608,'Anatol Rosenfeld',null);
insert into autores values (609,'Willi Bolle',null);
insert into autores values (610,'Anatol Rosenfeld',null);
insert into autores values (611,'Thomaz Farkas',null);
insert into autores values (612,'Lourival Gomes Machado',null);
insert into autores values (613,'Susan M. Daum',null);
insert into autores values (1613,'Jeanne Stellman',null);
insert into autores values (614,'Paulo Roberto Arruda de Menezes',null);
insert into autores values (615,'Ludwig Wittgenstein',null);
insert into autores values (616,'Maurice Debesse',null);
insert into autores values (1616,'Gaston Mialaret',null);
insert into autores values (617,'Ricardo Bento',null);
insert into autores values (1617,'Aroldo Miniti',null);
insert into autores values (2617,'Silvio Marone',null);
insert into autores values (618,'Carlos Eugênio Marcondes de Moura',null);
insert into autores values (619,'Wolf Lepenies',null);
insert into autores values (620,'Hayden White',null);
insert into autores values (621,'Marcos Antonio de Moraes',null);
insert into autores values (622,'Frank Kermode',null);
insert into autores values (623,'Flávio Ulhoa Coelho',null);
insert into autores values (1623,'Mary Lilian Lourenço',null);
insert into autores values (624,'Tadeu Chiarelli',null);
insert into autores values (625,'Reginaldo Prandi',null);
insert into autores values (626,'Elza Cunha de Vincenzo',null);
insert into autores values (627,'Gilberto Mendes',null);
insert into autores values (628,'Armando Sergio da Silva',null);
insert into autores values (629,'Anne Ellen Freeman',null);
insert into autores values (630,'Anthony Downs',null);
insert into autores values (631,'José Mindlin',null);
insert into autores values (632,'Maria Cecila Loschiavo Santos',null);
insert into autores values (633,'Philippe Willemart',null);
insert into autores values (634,'Otília B. F. Arantes',null);
insert into autores values (635,'Hélio Lourenço de Oliveira',null);
insert into autores values (636,'Vários autores',null);
insert into autores values (637,'Vários autores',null);
insert into autores values (638,'Mário Guimarães Ferri',null);
insert into autores values (1638,'Carl Axel Lindman',null);
insert into autores values (639,'Manuel Said Ali',null);
insert into autores values (640,'Sergio Stopatto',null);
insert into autores values (641,'Mário de Andrade',null);
insert into autores values (642,'Paulo Emílio Salles Gomes',null);
insert into autores values (643,'Márcia Faria Westphal',null);
insert into autores values (644,'José Luiz Goldfarb',null);
insert into autores values (645,'Márcia Cavendish Wanderley',null);
insert into autores values (646,'Sonnia Gu Sy Fiori',null);
insert into autores values (647,'Susana Kampff Lages',null);
insert into autores values (648,'Rudolf Haller',null);
insert into autores values (649,'Neusa Romero Barazal',null);
insert into autores values (650,'Afonso de Escragnolle Taunay',null);
